#!/bin/sh

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "This script must be run as root"
    exit -1
fi

# user:group splunk:splunk must exist
dscl . -read /Groups/_splunk 2>/dev/null >/dev/null && \
dscl . -read /Users/_splunk 2>/dev/null >/dev/null || exit -1

# set ownership and setuid+setgid bits
chown -R splunk:splunk /opt/splunkforwarder
chmod ug+s /opt/splunkforwarder/bin/splunk

# kill any running splunkd
[ ! -z "$(pgrep splunkd)" ] && killall splunkd

SPLUNK=/opt/splunkforwarder/bin/splunk

# Splunk First-Time-Run
/usr/bin/sudo -u _splunk ${SPLUNK} start --accept-license --auto-ports --no-prompt --answer-yes
sleep 3

# create a LaunchDaemon
${SPLUNK} enable boot-start -user _splunk
sleep 3

# stop the LaunchDaemon if running
launchctl bootout system /Library/LaunchDaemons/com.splunk.plist
sleep 3

# start the LaunchDaemon, which starts splunk
launchctl bootstrap system /Library/LaunchDaemons/com.splunk.plist

exit 0
